const codes = {
    title: "Code ISO | HTML | SYMBOLE",
    data: [
        {
            symbole:"espace",
            codeCla:" ",
            codeIso:"&#32;",
            unicode:"U+000A0;",
            codeHtml:"&#160;",
            htmlEntity:"&nbsp;",
            desc:"Espace",
            codeCss:"\\00A0",
            codeHex:"&#xa0;",
        },
        {
            symbole:"!",
            codeCla:"Alt+ 033",
            codeIso:"&#33;",
            unicode:"U+00021",
            codeHtml:"&#33;",
            htmlEntity:"&excl;",
            desc:"Pt. exclammation",
            codeCss:"\\0021",
            codeHex:"&#x21;",
        },
        {
            symbole:"\"",
            codeCla:"Alt+ 034",
            codeIso:"&#34;",
            unicode:"U+00022;",
            codeHtml:"&#34;",
            htmlEntity:"&quot;",
            desc:"Guiellemts double",
            codeCss:"\\0022",
            codeHex:"&#x22;",
        },
        {
            symbole:"#",
            codeCla:"Alt+ 035",
            codeIso:"&#35;",
            unicode:"U+00023",
            codeHtml:"&#35;",
            htmlEntity:"&num;",
            desc:"Carré ou dièse",
            codeCss:"\\0023",
            codeHex:"&#x23;",
        },
        {
            symbole:"$",
            codeCla:"Alt+ 036",
            codeIso:"&#36;",
            unicode:"U+00024",
            codeHtml:"&#36;",
            htmlEntity:"&dollar;",
            desc:"Dollar",
            codeCss:"\\0024",
            codeHex:"&#x24;",
        },
        {
            symbole:"%",
            codeCla:"Alt+ 037",
            codeIso:"&#37;",
            unicode:"U+00025",
            codeHtml:"&#37;",
            htmlEntity:"&percnt;",
            desc:"Pour cent",
            codeCss:"\\0025",
            codeHex:"&#x25;",
        },
        {
            symbole:"&",
            codeCla:"Alt+ 038",
            codeIso:"&#38;",
            unicode:"U+00026",
            codeHtml:"&#38;",
            htmlEntity:"&amp;",
            desc:"Et commercial",
            codeCss:"\\0026",
            codeHex:"&#x26;",
        },
        {
            symbole:"'",
            codeCla:"Alt+ 039",
            codeIso:"&#39;",
            unicode:"U+00027",
            codeHtml:"&#39;",
            htmlEntity:"&apos;",
            desc:"Apostrophe    ",
            codeCss:"\\0027",
            codeHex:"&#x27;",
        },
        {
            symbole:"(",
            codeCla:"Alt+ 040",
            codeIso:"&#40;",
            unicode:"U+00028",
            codeHtml:"&#40;",
            htmlEntity:"&lpar;",
            desc:"Parenthèse ouvrante",
            codeCss:"\\0028",
            codeHex:"&#x28;",
        },
        {
            symbole:")",
            codeCla:"Alt+ 041",
            codeIso:"&#41;",
            unicode:"U+00029",
            codeHtml:"&#41;",
            htmlEntity:"&rpar;",
            desc:"Parenthèse fermante",
            codeCss:"\\0029",
            codeHex:"&#x29;",
        },
        {
            symbole:"*",
            codeCla:"Alt+ 042",
            codeIso:"&#42;",
            unicode:"U+02217",
            codeHtml:"&#8727;",
            htmlEntity:"&lowast;",
            desc:"Flocon de neige",
            codeCss:"\\2217",
            codeHex:"&#x2217;",
        },
        {
            symbole:"×",
            codeCla:"Alt+ 0215",
            codeIso:"&#0215",
            unicode:"U+000D7",
            codeHtml:"&#215;",
            htmlEntity:"&times;",
            desc:"Multiplication",
            codeCss:"\\00D7",
            codeHex:"&#xd7;",
        },
        {
            symbole:"+",
            codeCla:"Alt+ 043",
            codeIso:"&#43;",
            unicode:"U+0002B",
            codeHtml:"&#43;",
            htmlEntity:"&plus;",
            desc:"Addition",
            codeCss:"\\002B",
            codeHex:"&#x2b;",
        },
        {
            symbole:",",
            codeCla:"Alt+ 044",
            codeIso:"&#44;",
            unicode:"U+0002C",
            codeHtml:"&#44;",
            htmlEntity:"&comma;",
            desc:"Virgule",
            codeCss:"\\002C",
            codeHex:"&#x2c;",
        },
        {
            symbole:"-",
            codeCla:"Alt+ 045",
            codeIso:"&#45;",
            unicode:"U+02212",
            codeHtml:"&#8722;",
            htmlEntity:"&minus;",
            desc:"Soustraction",
            codeCss:"\\2212",
            codeHex:"&#x2212;",
        },
        {
            symbole:".",
            codeCla:"Alt+ 046",
            codeIso:"&#46;",
            unicode:"U+0002E",
            codeHtml:"&#46;",
            htmlEntity:"&period;",
            desc:"Point",
            codeCss:"\\002E",
            codeHex:"&#x2e;",
        },
        {
            symbole:"/",
            codeCla:"Alt+ 047",
            codeIso:"&#47;",
            unicode:"U+0002F",
            codeHtml:"&#47;",
            htmlEntity:"&sol;",
            desc:"Slash",
            codeCss:"\\002F",
            codeHex:"&#x2f;",
        },
        {
            symbole:"0",
            codeCla:"Alt+ 048",
            codeIso:"&#48;",
            unicode:"U+00030",
            codeHtml:"&#48;",
            htmlEntity:"",
            desc:"Zero",
            codeCss:"\\0030",
            codeHex:"&#x30;;",
        },
        {
            symbole:"1",
            codeCla:"Alt+ 049",
            codeIso:"&#49;",
            unicode:"U+00031",
            codeHtml:"&#49;",
            htmlEntity:"",
            desc:"Un",
            codeCss:"\\0031",
            codeHex:"&#x31;;",
        },
        {
            symbole:"2",
            codeCla:"Alt+ 050",
            codeIso:"&#50;",
            unicode:"U+00032",
            codeHtml:"&#50;",
            htmlEntity:"",
            desc:"Deux",
            codeCss:"\\0032",
            codeHex:"&#x32;;",
        },
        {
            symbole:"3",
            codeCla:"Alt+ 051",
            codeIso:"&#51;",
            unicode:"U+00033",
            codeHtml:"&#51;",
            htmlEntity:"",
            desc:"Trois",
            codeCss:"\\0033",
            codeHex:"&#x33;;",
        },
    ]
};
export default codes;
