export { default as HeaderLayout } from './headerLayout';
export { default as HeroLayout } from './heroLayout';
export { default as FeaturesLayout } from './featuresLayout';
export { default as AboutLayout } from './aboutLayout';
export { default as ServiceLayout } from './serviceLayout';
export { default as DonationLayout } from './donationLayout';
export { default as PartnerLayout } from './partnerLayout';
export { default as EventLayout } from './enventLayout';
export { default as FooterLayout } from './footerLayout';